import type {
  ChoirEvent,
  GalleryItem,
  BlogPost,
  Program,
  EquipmentRecord,
} from '@/types/database';

const isoToday = () => new Date().toISOString();
const dateOffset = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export const placeholderEvents: ChoirEvent[] = [
  {
    id: 'evt-1',
    title: 'Sound of the Sanctuary — Worship Masterclass',
    description:
      'A two-day intensive for worship leaders covering vocal craft, set design, and pastoral leading.',
    audience: 'Worship leaders & teams',
    date: dateOffset(14),
    time: '09:00:00',
    venue: 'Adullam Cave HQ, Accra',
    capacity: 60,
    fee: 150,
    currency: 'GHS',
    is_online: false,
    status: 'scheduled',
    created_at: isoToday(),
  },
  {
    id: 'evt-2',
    title: 'Young Choristers Open Audition',
    description:
      'Open auditions for our incoming young choristers cohort. Bring a song and a willing heart.',
    audience: 'Ages 8–17',
    date: dateOffset(28),
    time: '14:00:00',
    venue: 'Adullam Cave HQ, Accra',
    capacity: 120,
    fee: 0,
    currency: 'GHS',
    is_online: false,
    status: 'scheduled',
    created_at: isoToday(),
  },
  {
    id: 'evt-3',
    title: 'Keys for the Kingdom — Online Piano Workshop',
    description:
      'A live online workshop on worship piano fundamentals — chord voicings, modulations, and feel.',
    audience: 'Pianists & keyboardists',
    date: dateOffset(45),
    time: '18:00:00',
    venue: 'Online (Zoom)',
    capacity: 200,
    fee: 80,
    currency: 'GHS',
    is_online: true,
    status: 'scheduled',
    created_at: isoToday(),
  },
];

export const placeholderPastEvents: ChoirEvent[] = [
  {
    id: 'past-1',
    title: 'Carols by Candlelight 2024',
    description: 'An evening of carols, candles, and consecrated worship.',
    audience: 'Public',
    date: dateOffset(-120),
    time: '19:00:00',
    venue: 'National Theatre, Accra',
    capacity: 800,
    fee: 0,
    currency: 'GHS',
    is_online: false,
    status: 'completed',
    created_at: isoToday(),
  },
  {
    id: 'past-2',
    title: 'Worship Leader Bootcamp III',
    description: 'A three-day immersive for emerging worship leaders.',
    audience: 'Worship leaders',
    date: dateOffset(-220),
    time: '09:00:00',
    venue: 'Kumasi',
    capacity: 80,
    fee: 200,
    currency: 'GHS',
    is_online: false,
    status: 'completed',
    created_at: isoToday(),
  },
];

export const placeholderPrograms: Program[] = [
  {
    id: 'prog-1',
    title: 'Young Choristers Foundation',
    description:
      'A year-long foundation in vocal craft, theory, and worship formation for young singers.',
    target_audience: 'youth',
    duration: '12 months',
    format: 'in_person',
    prerequisites: 'None — open to ages 8–17.',
    is_active: true,
    created_at: isoToday(),
  },
  {
    id: 'prog-2',
    title: 'Worship Leadership Track',
    description:
      'Equipping adult worship leaders with theology, musicianship, and pastoral skill.',
    target_audience: 'adult',
    duration: '9 months',
    format: 'hybrid',
    prerequisites: 'Active worship ministry experience preferred.',
    is_active: true,
    created_at: isoToday(),
  },
  {
    id: 'prog-3',
    title: 'Piano & Keyboard Mastery',
    description:
      'A practical journey from chords to confident worship-pianist competence.',
    target_audience: 'all',
    duration: '6 months',
    format: 'in_person',
    prerequisites: 'Basic note reading is helpful but not required.',
    is_active: true,
    created_at: isoToday(),
  },
  {
    id: 'prog-4',
    title: 'Organ for the Sanctuary',
    description: 'Foundational organ technique with hymn and worship application.',
    target_audience: 'all',
    duration: '4 months',
    format: 'in_person',
    prerequisites: 'Some piano background recommended.',
    is_active: true,
    created_at: isoToday(),
  },
];

const galleryImg = (seed: string, w = 900, h = 1200) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`;

export const placeholderGallery: GalleryItem[] = [
  {
    id: 'g-1',
    title: 'Sunday rehearsal',
    description: 'Choir blocking and harmony work.',
    category: 'rehearsals',
    media_type: 'image',
    file_url: galleryImg('cave-1', 1200, 900),
    thumbnail_url: galleryImg('cave-1', 600, 450),
    youtube_url: null,
    is_featured: true,
    is_published: true,
    date_taken: dateOffset(-30),
    created_at: isoToday(),
  },
  {
    id: 'g-2',
    title: 'Carols by Candlelight',
    description: 'Annual carol service.',
    category: 'performances',
    media_type: 'image',
    file_url: galleryImg('cave-2', 900, 1200),
    thumbnail_url: galleryImg('cave-2', 450, 600),
    youtube_url: null,
    is_featured: true,
    is_published: true,
    date_taken: dateOffset(-120),
    created_at: isoToday(),
  },
  {
    id: 'g-3',
    title: 'Keyboard rig installation',
    description: 'A new worship setup at a partner church.',
    category: 'equipment',
    media_type: 'image',
    file_url: galleryImg('cave-3', 1600, 900),
    thumbnail_url: galleryImg('cave-3', 800, 450),
    youtube_url: null,
    is_featured: true,
    is_published: true,
    date_taken: dateOffset(-60),
    created_at: isoToday(),
  },
  {
    id: 'g-4',
    title: 'Worship leaders workshop',
    description: 'Q&A panel with our facilitators.',
    category: 'workshops',
    media_type: 'image',
    file_url: galleryImg('cave-4', 900, 1100),
    thumbnail_url: galleryImg('cave-4', 450, 550),
    youtube_url: null,
    is_featured: true,
    is_published: true,
    date_taken: dateOffset(-90),
    created_at: isoToday(),
  },
  {
    id: 'g-5',
    title: 'Backstage prayer',
    description: 'Before the curtain rises.',
    category: 'community',
    media_type: 'image',
    file_url: galleryImg('cave-5', 1100, 900),
    thumbnail_url: galleryImg('cave-5', 550, 450),
    youtube_url: null,
    is_featured: true,
    is_published: true,
    date_taken: dateOffset(-15),
    created_at: isoToday(),
  },
  {
    id: 'g-6',
    title: 'Children\u2019s choir performance',
    description: 'Our youngest voices.',
    category: 'events',
    media_type: 'image',
    file_url: galleryImg('cave-6', 900, 1300),
    thumbnail_url: galleryImg('cave-6', 450, 650),
    youtube_url: null,
    is_featured: true,
    is_published: true,
    date_taken: dateOffset(-7),
    created_at: isoToday(),
  },
  {
    id: 'g-7',
    title: 'Tuning before service',
    description: 'Instrumentalists warming up.',
    category: 'rehearsals',
    media_type: 'image',
    file_url: galleryImg('cave-7', 1200, 800),
    thumbnail_url: galleryImg('cave-7', 600, 400),
    youtube_url: null,
    is_featured: false,
    is_published: true,
    date_taken: dateOffset(-40),
    created_at: isoToday(),
  },
  {
    id: 'g-8',
    title: 'Sound system commissioning',
    description: 'Final calibration at a new install.',
    category: 'equipment',
    media_type: 'image',
    file_url: galleryImg('cave-8', 1500, 1000),
    thumbnail_url: galleryImg('cave-8', 750, 500),
    youtube_url: null,
    is_featured: false,
    is_published: true,
    date_taken: dateOffset(-50),
    created_at: isoToday(),
  },
  {
    id: 'g-9',
    title: 'Live concert highlight',
    description: 'A moment we won\u2019t forget.',
    category: 'performances',
    media_type: 'youtube',
    file_url: null,
    thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    is_featured: false,
    is_published: true,
    date_taken: dateOffset(-150),
    created_at: isoToday(),
  },
];

export const placeholderBlog: BlogPost[] = [
  {
    id: 'b-1',
    title: 'Why we still call ourselves a Cave',
    slug: 'why-we-call-ourselves-cave',
    content: '',
    excerpt:
      'Long before the lights and the live streams, there was a cave — a place of consecration.',
    cover_image_url: galleryImg('blog-1', 1200, 800),
    is_published: true,
    published_at: dateOffset(-10),
    author_id: null,
    created_at: isoToday(),
  },
  {
    id: 'b-2',
    title: '5 vocal warm-ups every chorister should know',
    slug: 'vocal-warmups',
    content: '',
    excerpt: 'Simple, daily routines that build healthy voices over the long arc.',
    cover_image_url: galleryImg('blog-2', 1200, 800),
    is_published: true,
    published_at: dateOffset(-25),
    author_id: null,
    created_at: isoToday(),
  },
  {
    id: 'b-3',
    title: 'Installing sound for worship: a 10-step framework',
    slug: 'sound-install-framework',
    content: '',
    excerpt: 'How we approach every audio install — from listening to commissioning.',
    cover_image_url: galleryImg('blog-3', 1200, 800),
    is_published: true,
    published_at: dateOffset(-40),
    author_id: null,
    created_at: isoToday(),
  },
];

export const placeholderEquipment: EquipmentRecord[] = [
  {
    id: 'eq-1',
    church_name: 'Grace Tabernacle, East Legon',
    location: 'Accra',
    service_date: dateOffset(-90),
    equipment_types: ['Sound System', 'Keyboards', 'Stage Monitors'],
    notes: 'Full sanctuary audio install with new keyboard rig and tech-team training.',
    status: 'completed',
    created_at: isoToday(),
  },
  {
    id: 'eq-2',
    church_name: 'Living Word Chapel, Tema',
    location: 'Tema',
    service_date: dateOffset(-180),
    equipment_types: ['Piano', 'Organ'],
    notes: 'Acoustic piano relocation and pipe-organ tuning.',
    status: 'completed',
    created_at: isoToday(),
  },
  {
    id: 'eq-3',
    church_name: 'Hope Sanctuary, Kumasi',
    location: 'Kumasi',
    service_date: dateOffset(-260),
    equipment_types: ['Sound System'],
    notes: 'Speaker array redesign and acoustic tuning of main hall.',
    status: 'completed',
    created_at: isoToday(),
  },
];
